#!/usr/bin/env bash

# Construct the dmenu command with color options
dmenu_command="dmenu -c -bw 3 -i -l 4 "

# Function to get current volume

get_brightness() {
    brightnessctl | grep -oP '\d+%' | head -1 | tr -d '%'
}

# Function to set volume
set_brightness() {
    brightnessctl set "$1%" > /dev/null
}

# Function to display current volume
display_brightness() {
    current_vol=$(get_brightness)
    # Clear previous line and print new volume
    dunstify -t 500 "Current Brightness: ${current_vol}%"
    # dunstify "Current Volume: ${current_vol}% [j: decrease, k: increase, q: quit]"
}

while true; do
  xinput test-xi2 --root 3 | grep -A3 --line-buffered RawKeyRelease | while read -r line;
	do
		if [[ $line == *"detail"* ]];
		then
			key=$( echo $line | sed "s/[^0-9]*//g")
			case "$key" in
				44)
					current_brightness=$(get_brightness)
					new_bright=$((current_brightness - 5)) # Decrease by 5%
					if [ "$new_bright" -lt 0 ]; then
						new_bright=0
					fi
					set_brightness "$new_bright"
					display_brightness
					;;
				45)
					current_brightness=$(get_brightness)
					new_bright=$((current_brightness + 5))
					if [ "$new_bright" -gt 100 ]; then
						new_bright=100
					fi
					set_brightness "$new_bright"
					display_brightness
					;;
				24)
					break
					;;
				*)
					display_brightness
					;;
			esac
		fi
		#Do something with the key

	done
	break
done
