#!/usr/bin/env bash

# Auto-mount has been set up in services.udev on NixOS using
# 	services.udev = {
#		extraRules = ''
#			ACTION=="add", KERNEL=="sd[a-e][0-9]", ENV{ID_FS_UUID}=="3039-3932", RUN+="${pkgs.systemd}/bin/systemd-mount --no-block -A -G -o gid=users,fmask=113,dmask=002 /dev/%k /mnt/sdcard"
#		'';
#	};


# Use dunstify if available, otherwise fall back to notify-send
NOTIFY_CMD=$(which dunstify || which notify-send)

folder=~/bilder

mount() { # Check if the card is mounted
	[ -d /mnt/sdcard/DCIM/ ] || $NOTIFY_CMD "Card not mounted."
}


unmount() { # Unmount card
		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFY_CMD "Card unmounted."
}


dt() { # Open darktable to import today's photos
		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFY_CMD "Card unmounted; opening Darktable"
		(darktable "$folder$(date '+%b_%d')") &
}


postrun() { # Menu to select what I want to do after photos have been transferred
		$NOTIFY_CMD "Photos have transferred."
		choice=$(printf "Unmount card\\nOpen Darktable, unmount\\nDo nothing" | dmenu -c -l 3 -i -p "Photos have transferred: ")
		case "$choice" in
				Unmount*) unmount;;
				Open*) dt;;
				Do*) exit 0;;
		esac
}


auto() { # Transfer photos from SD card into a directory for today's date
		[ -d /mnt/sdcard/DCIM/ ] || exit 0
		$NOTIFY_CMD "Photo transfer starting..."

		mkdir -p "$folder$(date '+%b_%d')"
		find /mnt/sdcard -type f -name "*.CR2" -exec mv -nv {} "$folder$(date '+%F')/" \; && postrun
}


case "$1" in
		mount) mount ;;
		unmount) unmount ;;
		dt) dt ;;
		*) auto ;;
esac
