#!/usr/bin/env bash
shopt -s nocasematch

dir=~/videor/to-watch/
seen_dir="$HOME/videor/seen/"
mkdir -p $seen_dir

(eza --no-quotes "$dir") | rofi -dmenu -i -l 10 -p delete | while IFS= read -r selection; do
    [[ -n "$selection" ]] && rm "$dir$selection"
	echo "$selection - $(date '+%F %T')" >> "$seen_dir/watch_history"
done
