#!/usr/bin/env bash

dmenu_command="wmenu -l 6 -p system"
download=" get video"
delete=" delete video"
bluetooth=" bluetooth"
kill=" kill process"
reboot=" reboot"
shutdown=" power"

chosen=$(printf "$download\n$delete\n$bluetooth\n$kill\n$reboot\n$shutdown" | eval "$dmenu_command")

case "$chosen" in
	"$download")
		/home/fw/scripts/download
		;;
	"$delete")
		/home/fw/scripts/delete-video
		;;
  "$kill")
    kill_command="wmenu -i -l 10 -p Kill:"
    pid_to_kill=$(ps -u "$USER" -o pid,comm,%cpu,%mem | eval "$kill_command" | awk '{print $1}')
    if [ -n "$pid_to_kill" ]; then
      xargs -r kill <<< "$pid_to_kill"
    fi
    ;;
  "$reboot")
    systemctl reboot -i
    ;;
  "$shutdown")
    shutdown now
    ;;
  "$bluetooth")
	  /home/fw/scripts/bluetooth
    ;;
  *)
    exit 1
    ;;
esac
