#!/usr/bin/env bash

# Construct the dmenu command with color options
dmenu_command="dmenu -c -bw 3 -i -l 6 "

chosen=$(printf "kill\nzzz\nreboot\nshutdown\ndownload\nwatch" | eval "$dmenu_command")

case "$chosen" in
	download)
		/home/fw/scripts/download
		;;
	watch)
		/home/fw/scripts/watch
		;;
  kill)
    kill_command="dmenu -c -bw 3 -i -l 10 -p Kill:"
    pid_to_kill=$(ps -u "$USER" -o pid,comm,%cpu,%mem | eval "$kill_command" | awk '{print $1}')
    if [ -n "$pid_to_kill" ]; then
      xargs -r kill <<< "$pid_to_kill"
    fi
    ;;
  zzz)
    slock -m "$(cowsay "$(fortune)" | lolcat -ft)" &
    systemctl suspend -i
    ;;
  reboot)
    systemctl reboot -i
    ;;
  shutdown)
    shutdown now
    ;;
  *)
    exit 1
    ;;
esac
