#!/usr/bin/env bash
shopt -s nocasematch

dir=~/videor/to-watch/

# Build the selection list and map it to full filenames
# url=$(dmenu -i -c -bw 3 -p Download)
url="$(echo "" | eval "rofi -dmenu -i -p download:" <&-)" || exit 0

[[ -n "$url" ]] && yt-dlp -o "$dir%(title)s - %(uploader)s" "$url" --extractor-args "youtube:player_js_version=actual"
