#!/usr/bin/env bash
shopt -s nocasematch

dir=~/videor/

# Build the selection list and map it to full filenames
# url=$(dmenu -i -c -bw 3 -p Download)
dmenu_command="dmenu -i -c -bw 3 -p Download"
url=$(printf "" | eval "$dmenu_command")

[[ -n "$url" ]] && yt-dlp -o "$dir%(title)s - %(uploader)s" "$url"
