#!/usr/bin/env bash

# Construct the dmenu command with color options
dmenu_command="dmenu -c -bw 3 -i -l 4 "

get_volume() {
    amixer get Master | grep -oP '\d+%' | head -1 | tr -d '%'
}

# Function to set volume
set_volume() {
    pactl set-sink-volume @DEFAULT_SINK@ "$1%" > /dev/null
}

# Function to display current volume
display_volume() {
    current_vol=$(get_volume)
    # Clear previous line and print new volume
    dunstify -t 500 "Current Volume: ${current_vol}%"
    # dunstify "Current Volume: ${current_vol}% [j: decrease, k: increase, q: quit]"
}

while true; do
  xinput test-xi2 --root 3 | grep -A3 --line-buffered RawKeyRelease | while read -r line;
	do
		if [[ $line == *"detail"* ]];
		then
			key=$( echo $line | sed "s/[^0-9]*//g")
	case "$key" in
		44)
			current_vol=$(get_volume)
			new_vol=$((current_vol - 5)) # Decrease by 5%
			if [ "$new_vol" -lt 0 ]; then
				new_vol=0
			fi
			set_volume "$new_vol"
			display_volume
			;;
		45)
			current_vol=$(get_volume)
			new_vol=$((current_vol + 5)) # Increase by 5%
			if [ "$new_vol" -gt 100 ]; then
				new_vol=100
			fi
			set_volume "$new_vol"
			display_volume
			;;
		24)
			break
			;;
		*)
			display_volume
			;;
		
	esac
	fi
done
break
done
