#!/usr/bin/env bash
shopt -s nocasematch

dir=~/videor/

(eza --no-quotes "$dir") | grep -E '\.webm' | dmenu -i -c -l 5 -bw 3 -p Watch | while IFS= read -r selection; do
    [[ -n "$selection" ]] && devour mpv "$dir$selection"
done
