#!/usr/bin/env bash
shopt -s nocasematch

dir=~/videor/to-watch/

(eza --no-quotes "$dir") | grep -E '\.webm' | wmenu -i -l 10 -p watch: | while IFS= read -r selection; do
    [[ -n "$selection" ]] && devour mpv "$dir$selection"
done
